"""Abstract tensor kernel.

The objects exported here are backend-independent semantic declarations.  They
are deliberately separate from coordinate components and from SymPy-backed
older SymPy-backed helper layers so that xAct/Cadabra-class canonicalization can build on a
small, stable IR.
"""
from .manifolds import Manifold, TensorBundle, TensorKernelError, VectorBundle
from .indices import AbstractIndex, IndexType
from .symmetries import SlotSymmetry
from .tensor_heads import TensorHead
from .tensor_expr import TensorExpr, TensorFactor, TensorTerm, canonicalize
from .conventions import (
    CliffordConvention,
    CurvatureConvention,
    GeometryConvention,
    HodgeConvention,
    SignatureConvention,
    default_lorentzian_convention,
    default_riemannian_convention,
)
from .permutation_group_backend import (
    CanonicalDoubleCosetResult,
    CanonicalizationBackend,
    Permutation,
    PermutationGroup,
    PythonPermutationBackend,
    SignedPermutation,
    SiftResult,
    StabilizerChain,
    brute_force_double_coset,
    canonical_double_coset_reference,
    default_permutation_backend,
    schreier_generators,
    schreier_sims,
)
from .permutation_canonicalization import (
    CanonicalizationReport,
    canonicalize_expression as canonicalize_expression_strong,
    canonicalize_monoterm,
)

from .tensor_monomial_encoding import (
    CommonCaseAnalysis,
    DecodedCanonicalMonomial,
    DummyPairBlock,
    DummyRenamingPolicy,
    EncodedTensorMonomial,
    SlotMetadata,
    TensorCanonicalizationOracleResult,
    TensorCanonicalizationResult,
    analyze_common_canonicalization_cases,
    build_dummy_renaming_group,
    build_slot_symmetry_group,
    canonicalize_encoded_monomial,
    canonicalize_repeated_factors,
    canonicalize_tensor,
    canonicalize_tensor_expression,
    canonicalize_tensor_term,
    canonicalize_total_symmetry_blocks,
    compare_encoded_canonicalization_to_oracle,
    decode_canonical_result,
    decompose_dummy_pair_blocks,
    encode_tensor_monomial,
    repeated_factor_blocks,
    select_canonicalization_base,
)

from .tensor_identities import (
    epsilon_product_to_generalized_delta,
    generalized_delta_expansion,
    generalized_delta_head,
    levi_civita_head,
)
from .realization import ComponentRealizationRegistry, realize_tensor_expression
from .derivatives import DerivativeOperator, commutator, covariant_derivative, partial_derivative
from .curvature import apply_first_bianchi, curvature_heads, first_bianchi_identity, is_first_bianchi_sum

from .components import (
    Basis,
    BasisTransform,
    Coframe,
    ComponentTensor,
    ConnectionCoefficients,
    CoordinateSystem,
    CoordinateTransform,
    MetricGeometry,
    SpinConnectionCoefficients,
    Vielbein,
    christoffel_symbols_from_metric,
    coordinate_symbols,
    covariant_derivative_components,
    dual_coframe,
    einstein_component_tensor,
    inverse_metric_component_tensor,
    inverse_metric_from_metric,
    lower_riemann_tensor,
    metric_component_tensor,
    metric_geometry,
    generalized_delta_component_tensor,
    levi_civita_symbol_component_tensor,
    ricci_component_tensor,
    riemann_component_tensor,
    scalar_curvature_component,
    spin_connection_from_vielbein,
)

from .coordinate_tools import (
    CoordinateDomain,
    CoordinateMap,
    CoordinateSingularity,
    StandardCoordinateEntry,
    list_standard_coordinates,
    standard_coordinate_catalog,
    standard_coordinate_entry,
    standard_coordinate_map_to_cartesian,
    standard_coordinate_system,
    standard_metric,
    coordinate_domain_assumptions,
    coordinate_map_between,
    complete_coordinate_metadata,
    infer_coordinate_singularities,
)
from .vector_calculus import (
    VectorCalculusResult,
    curl as coordinate_curl,
    curl_result as coordinate_curl_result,
    divergence as coordinate_divergence,
    gradient as coordinate_gradient,
    hessian as coordinate_hessian,
    hessian_result as coordinate_hessian_result,
    laplacian as coordinate_laplacian,
    laplacian_result as coordinate_laplacian_result,
    levi_civita_connection,
    scalar_laplacian,
    tensor_laplacian,
    vector_laplacian,
    componentwise_laplacian,
    coordinate_to_physical_vector,
    physical_to_coordinate_vector,
    physical_curl,
    scale_factors,
)

from .coordinate_map_data import (
    CoordinateMapData,
    InverseBranch,
    catalog_transition_map,
    coordinate_map_data,
    coordinate_transform_graph,
    solve_inverse_branches,
    standard_coordinate_system_data,
)
from .field_transformations import (
    FieldTransformationResult,
    transform_covector_field,
    transform_scalar_field,
    transform_tensor_density,
    transform_tensor_field,
    transform_vector_field,
    transform_field,
)
from .symbolic_arrays import (
    TensorArray,
    as_tensor_array,
    tensor_contract,
    tensor_dimensions,
    tensor_map_components,
    tensor_product,
    tensor_properties,
    tensor_transpose,
)

from .exterior_forms import (
    DifferentialForm,
    basis_one_form,
    cartan_identity_residual,
    codifferential,
    de_rham_laplacian,
    exterior_derivative as exterior_derivative_form,
    exterior_derivative_squared,
    form_from_components,
    hodge_star,
    hodge_star_square_sign,
    hodge_star_squared,
    form_inner_product,
    is_closed,
    lie_derivative,
    pullback_from_coordinate_functions,
    wedge_hodge_inner_product,
    pullback_form,
    volume_form,
    wedge as wedge_forms,
)

from .variational_calculus import (
    BoundaryTerm,
    EulerLagrangeResult,
    IntegrationByPartsResult,
    PerturbationRule,
    PerturbativeExpression,
    PerturbativeTerm,
    binomial_perturbation_coefficients,
    christoffel_variation,
    coefficient_of_factor,
    derivative_of_expression,
    einstein_hilbert_metric_variation_density,
    euler_lagrange_expression,
    expand_metric_perturbation_to_order,
    integrate_by_parts_once,
    integrate_by_parts_once_with_boundary,
    inverse_metric_variation,
    metric_density_variation,
    metric_gauge_variation,
    perturbative_expand,
    ricci_variation,
    scalar_curvature_variation,
    stress_energy_from_metric_variation,
    variation_head,
    variation_of_factor,
    vary,
)


from .graded_algebra import (
    CliffordAlgebra,
    GaugeAlgebra,
    GradedProduct,
    GradedSymbol,
    SpinorIndexFamily,
    graded_commutator,
)

from .multiterm_identities import (
    LinearIdentity,
    MultitermReductionSystem,
    ReductionResult,
    ReductionTraceStep,
    antisymmetrized_identity,
    cyclic_identity,
    dimension_dependent_antisymmetry_identity,
    first_bianchi_reduction_system,
    identity_from_expression,
    term_coefficient_map,
    identity_basis,
    generate_renaming_orbit,
    expression_from_coefficient_map,
    IdentityBasis,
    identity_orbit,
    identity_closure,
    echelon_identity_basis,
    normal_form,
    normal_form_with_trace,
    reduce_first_bianchi,
    reduce_multiterm,
    reduce_multiterm_with_trace,
    schouten_identity,
    weyl_ricci_scalar_decomposition_identity,
    young_antisymmetry_identity,
    young_row_symmetry_identity,
)

__all__ = [
    "schreier_sims",
    "StabilizerChain",
    "SignedPermutation",
    "PermutationGroup",
    "Permutation",
    "CanonicalDoubleCosetResult",
    "SiftResult",
    "CanonicalizationBackend",
    "PythonPermutationBackend",
    "brute_force_double_coset",
    "default_permutation_backend",
    "schreier_generators",
    "tensor_transpose",
    "tensor_properties",
    "tensor_product",
    "tensor_map_components",
    "tensor_dimensions",
    "tensor_contract",
    "as_tensor_array",
    "TensorArray",
    "transform_field",
    "transform_vector_field",
    "transform_tensor_field",
    "transform_tensor_density",
    "transform_scalar_field",
    "transform_covector_field",
    "FieldTransformationResult",
    "standard_coordinate_system_data",
    "solve_inverse_branches",
    "coordinate_transform_graph",
    "coordinate_map_data",
    "catalog_transition_map",
    "InverseBranch",
    "CoordinateMapData",
    "SignatureConvention",
    "CurvatureConvention",
    "HodgeConvention",
    "CliffordConvention",
    "GeometryConvention",
    "default_riemannian_convention",
    "default_lorentzian_convention",
    "CanonicalizationReport",
    "canonicalize_expression_strong",
    "canonicalize_monoterm",
    "levi_civita_head",
    "generalized_delta_head",
    "generalized_delta_expansion",
    "epsilon_product_to_generalized_delta",
    "ComponentRealizationRegistry",
    "realize_tensor_expression",
    "generalized_delta_component_tensor",
    "levi_civita_symbol_component_tensor",
    "CoordinateDomain",
    "CoordinateMap",
    "CoordinateSingularity",
    "StandardCoordinateEntry",
    "list_standard_coordinates",
    "standard_coordinate_catalog",
    "standard_coordinate_entry",
    "standard_coordinate_map_to_cartesian",
    "standard_coordinate_system",
    "standard_metric",
    "coordinate_curl",
    "coordinate_divergence",
    "coordinate_gradient",
    "coordinate_hessian",
    "coordinate_laplacian",
    "levi_civita_connection",
    "scalar_laplacian",
    "tensor_laplacian",
    "vector_laplacian",
    "CliffordAlgebra",
    "GaugeAlgebra",
    "GradedProduct",
    "GradedSymbol",
    "SpinorIndexFamily",
    "graded_commutator",
    "BoundaryTerm",
    "IntegrationByPartsResult",
    "coefficient_of_factor",
    "integrate_by_parts_once_with_boundary",
    "stress_energy_from_metric_variation",
    "metric_gauge_variation",
    "form_inner_product",
    "wedge_hodge_inner_product",
    "is_closed",
    "pullback_from_coordinate_functions",
    "echelon_identity_basis",
    "normal_form",
    "normal_form_with_trace",
    "weyl_ricci_scalar_decomposition_identity",
    "christoffel_variation",
    "ricci_variation",
    "scalar_curvature_variation",
    "einstein_hilbert_metric_variation_density",
    "expand_metric_perturbation_to_order",
    "exterior_derivative_squared",
    "cartan_identity_residual",
    "hodge_star_squared",
    "hodge_star_square_sign",
    "pullback_form",
    "young_antisymmetry_identity",
    "young_row_symmetry_identity",
    "identity_closure",
    "term_coefficient_map",
    "identity_basis",
    "generate_renaming_orbit",
    "expression_from_coefficient_map",
    "IdentityBasis",
    "vary",
    "variation_of_factor",
    "variation_head",
    "perturbative_expand",
    "metric_density_variation",
    "inverse_metric_variation",
    "integrate_by_parts_once",
    "euler_lagrange_expression",
    "derivative_of_expression",
    "binomial_perturbation_coefficients",
    "PerturbativeTerm",
    "PerturbativeExpression",
    "PerturbationRule",
    "EulerLagrangeResult",
    "Coframe",
    "SpinConnectionCoefficients",
    "Vielbein",
    "covariant_derivative_components",
    "dual_coframe",
    "spin_connection_from_vielbein",
    "DifferentialForm",
    "exterior_derivative_form",
    "form_from_components",
    "wedge_forms",
    "reduce_multiterm",
    "reduce_multiterm_with_trace",
    "reduce_first_bianchi",
    "identity_from_expression",
    "antisymmetrized_identity",
    "cyclic_identity",
    "dimension_dependent_antisymmetry_identity",
    "identity_orbit",
    "schouten_identity",
    "ReductionResult",
    "ReductionTraceStep",
    "first_bianchi_reduction_system",
    "MultitermReductionSystem",
    "LinearIdentity",
    "volume_form",
    "lie_derivative",
    "hodge_star",
    "de_rham_laplacian",
    "codifferential",
    "basis_one_form",
    "CoordinateTransform",
    "MetricGeometry",
    "christoffel_symbols_from_metric",
    "coordinate_symbols",
    "einstein_component_tensor",
    "inverse_metric_from_metric",
    "lower_riemann_tensor",
    "metric_geometry",
    "ricci_component_tensor",
    "riemann_component_tensor",
    "scalar_curvature_component",
    "metric_component_tensor",
    "inverse_metric_component_tensor",
    "CoordinateSystem",
    "ConnectionCoefficients",
    "ComponentTensor",
    "BasisTransform",
    "Basis",
    "AbstractIndex",
    "IndexType",
    "Manifold",
    "SlotSymmetry",
    "TensorBundle",
    "DerivativeOperator",
    "TensorExpr",
    "TensorFactor",
    "TensorHead",
    "TensorKernelError",
    "TensorTerm",
    "VectorBundle",
    "apply_first_bianchi",
    "canonicalize",
    "curvature_heads",
    "first_bianchi_identity",
    "is_first_bianchi_sum",
    "commutator",
    "covariant_derivative",
    "partial_derivative",
    "canonical_double_coset_reference",
    "TensorCanonicalizationResult",
    "canonicalize_tensor",
    "VectorCalculusResult",
    "coordinate_curl_result",
    "coordinate_hessian_result",
    "coordinate_laplacian_result",
]
